volumes:
  data:
    driver: local
  logs:
    driver: local

services:
  api:
    build: .
    image: api-tagihan-wifi:1.0
    container_name: api-tagihan-wifi
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      APP_HOST: 0.0.0.0
    volumes:
      - data:/app/data
      - logs:/app/logs